version: 0.2
run-as: root

phases:

  install:
    commands:
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl   
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - source ~/.bashrc
      - echo 'Check kubectl version'
      - kubectl version --short --client
      - chmod +x ./prereqs.sh
      - sh ./prereqs.sh

  pre_build:
    commands:
      - echo Logging in to Amazon EKS...
      - aws eks --region us-east-1 update-kubeconfig --name demo
      

  build:
    commands:
      - echo Build started on `date`
      - eksctl create iamidentitymapping --cluster demo --arn arn:aws:iam::554515569705:role/CodeBuildKubectlRole --group system:masters --username CodeBuildKubectlRole
      - eksctl create iamidentitymapping --cluster demo --arn arn:aws:iam::554515569705:user/Kishan --group system:masters --username kishan
      - echo check config
      - kubectl config view --minify
      - echo check kubectl access
      - kubectl get svc

  post_build:
    commands:
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - kubectl rollout restart -f deployment.yaml
      - kubectl get svc 
